# Generated by Django 3.2.6 on 2021-08-17 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='user_profile',
            new_name='contacts',
        ),
    ]
