# Generated by Django 3.2.6 on 2021-08-12 13:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210811_1219'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='user',
            unique_together={('username', 'email')},
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('logo', models.ImageField(default='/media/users/default/logo.png', upload_to='media/default/<django.db.models.fields.UUIDField>/logo/')),
                ('location', models.CharField(blank=True, max_length=200, null=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
